Logging different dir structures with original workflow

diff --git a/.github/workflows/run-tests-workflow.yml b/.github/workflows/run-tests-workflow.yml
--- a/.github/workflows/run-tests-workflow.yml
+++ b/.github/workflows/run-tests-workflow.yml
@@ -107,21 +107,17 @@ jobs:
         run: |
           mv /tmp/linux_distribution ./resources/distribution
           npm run package
+          rm -rf ./resources/distribution
           VSIX_FILE=$(find /__w/vector-vscode-vcast/vector-vscode-vcast/ -maxdepth 1 -name "*.vsix" | grep -vE '\.(linux|windows)\.vsix' | head -n 1)
           NEW_VSIX_FILE="${VSIX_FILE%.vsix}.linux.vsix"
           mv $VSIX_FILE $NEW_VSIX_FILE
           echo "LINUX_VSIX_FILE=$NEW_VSIX_FILE" >> $GITHUB_ENV
 
-      - name: Prepare /vcast/vsix and copy VSIX
-        shell: bash
-        run: |
-          mkdir -p /vcast/vsix
-          cp "$LINUX_VSIX_FILE" "/vcast/vsix/$(basename "$LINUX_VSIX_FILE" .linux.vsix).vsix"
-
       - name: Package with VSCE - Windows
         run: |
           mv /tmp/win_distribution ./resources/distribution
           npm run package
+          rm -rf ./resources/distribution
           VSIX_FILE=$(find /__w/vector-vscode-vcast/vector-vscode-vcast/ -maxdepth 1 -name "*.vsix" | grep -vE '\.(linux|windows)\.vsix' | head -n 1)
           NEW_VSIX_FILE="${VSIX_FILE%.vsix}.win.vsix"
           mv $VSIX_FILE $NEW_VSIX_FILE
@@ -203,6 +199,7 @@ jobs:
              URL="$ARTIFACTORY_URL/VectorCAST-Reqs2Tests-Linux.tar.gz"
              curl -H "X-JFrog-Art-Api:${{ secrets.ARTIFACTORY_TOKEN }}" -X PUT $URL -T ../VectorCAST-Reqs2Tests-Linux.tar.gz
              echo "[Download distribution - Linux]($URL)" >> $GITHUB_STEP_SUMMARY
+             rm *.vsix
           else
              echo "Unable to build distribution for Linux" >> $GITHUB_STEP_SUMMARY
           fi
@@ -220,23 +217,6 @@ jobs:
           fi
           
           cd .. && rm -rf .distribution VectorCAST-Reqs2Tests-*.tar.gz
-        
-      - name: Debug: List files in all relevant directories
-        run: |
-          echo "/__w/vector-vscode-vcast/vector-vscode-vcast"
-          ls -lR /__w/vector-vscode-vcast/vector-vscode-vcast || echo "Not found"
-
-          echo "rds/vector-vscode-vcast"
-          ls -lR rds/vector-vscode-vcast || echo "Not found"
-
-          echo "/tmp/linux_distribution"
-          ls -lR /tmp/linux_distribution || echo "Not found"
-
-          echo ""./resources/distribution"
-          ls -lR ./resources/distribution || echo "Not found"
-
-          echo "/vcast/vsix"
-          ls -lR /vcast/vsix || echo "Not found"
 
       - name: Upload coverage artifact
         if: ${{ always() && strategy.job-index == '0' }}
@@ -278,6 +258,22 @@ jobs:
           -H "Content-Type: application/octet-stream" \
           $upload_url \
           --data-binary "@${{ env.WIN_VSIX_FILE }}"
+        - name: Debug: List files in all relevant directories
+          run: |
+            echo "/__w/vector-vscode-vcast/vector-vscode-vcast"
+            ls -lR /__w/vector-vscode-vcast/vector-vscode-vcast || echo "Not found"
+
+            echo "rds/vector-vscode-vcast"
+            ls -lR rds/vector-vscode-vcast || echo "Not found"
+
+            echo "/tmp/linux_distribution"
+            ls -lR /tmp/linux_distribution || echo "Not found"
+
+            echo "./resources/distribution"
+            ls -lR ./resources/distribution || echo "Not found"
+
+            echo "/vcast/vsix"
+            ls -lR /vcast/vsix || echo "Not found"
 
 
   generate-e2e-matrix:
