Adding new e2e tests (#11)
* Add debug flag to get debug info from cli outputs

* First req tests

* First requirements tests

* Finished first tests

* Using LINUX_VSIX_FILE as base dir

* Added requirements tests for manage

* Added Logs for test

* New path for CI

* Trying different path

* Trying normal path

* Path change

* Trying to copy vsix

* Decomment

* Trying temp folder

* Deleted unused var

* Different path

* Trying to find all correct folders

* Trying different path

* Additional log

* Trying to not remove the resources folder

* Logging different dir structures

* Logging different dir structures with original workflow

* Reset workflow file

* Logging important dir

* Reset workflow file

* Manage + Requirements tests

* Adding logs to multiple possible github resource locations

* Maximizing output view

* Trying to copy resources

* Trying to copy resources 2

* Trying to copy resources 3

* Trying to extract tar into dir

* Trying to extract tar into dir 2

* Trying to extract tar into dir 3

* Typo

* Trying other paths

* Trying to copy in other dir

* Trying with GUTHUB_WORKSPACE

* Trying to copy stuff from ./resources/distribution

* Trying to upload distirbution

* Trying to do the same steps for e2e

* path changes

* changed build spec

* Restoring prio workflow file

* Minor changes for tests

* Added pause to change outputview

* Trying to reopen channel

* Trying to select channel differently

* Trying to select channel differentl 2

* Select changes

* Changed channel selection

* Remove `vcast_requirements_manage.test.ts` and associated references in `specs_config.ts`.

---------

Co-authored-by: Patrick Bareiss <Patrick.Bareiss@vector.com>
Co-authored-by: Denis Moslavac <Denis.Moslavac@vector.com>

diff --git a/.github/workflows/run-tests-workflow.yml b/.github/workflows/run-tests-workflow.yml
--- a/.github/workflows/run-tests-workflow.yml
+++ b/.github/workflows/run-tests-workflow.yml
@@ -359,6 +359,40 @@ jobs:
           path: |
             node_modules
           key: ${{ runner.os }}-dependencies-${{ hashFiles('package.json') }}
+      
+      - name: Pull latest reqs2tests release
+        shell: bash
+        run: |
+          python3 ./ci/get_most_recent_reqs2tests_distribution.py
+          if [ ! -f "autoreq-linux.tar.gz" ]; then
+            echo "Error: autoreq-linux.tar.gz not found."
+            exit 1
+          fi
+          if [ ! -f "autoreq-win.tar.gz" ]; then
+            echo "Error: autoreq-win.tar.gz not found."
+            exit 1
+          fi
+          tar -xf autoreq-linux.tar.gz > /dev/null && rm autoreq-linux.tar.gz       
+          mv distribution /tmp/linux_distribution
+
+          mkdir -p "$GITHUB_WORKSPACE/vsix/resources/distribution"
+          cp -r /tmp/linux_distribution/* "$GITHUB_WORKSPACE/vsix/resources/distribution/"
+
+          tar -xf autoreq-win.tar.gz > /dev/null && rm autoreq-win.tar.gz
+          mv distribution /tmp/win_distribution
+
+      - name: Package with VSCE - Linux
+        run: |
+          mv /tmp/linux_distribution ./resources/distribution
+          npm run package
+
+          echo "Contents of $GITHUB_WORKSPACE/vsix/resources/distribution:"
+          ls -R $GITHUB_WORKSPACE/vsix/resources/distribution
+
+          VSIX_FILE=$(find /__w/vector-vscode-vcast/vector-vscode-vcast/ -maxdepth 1 -name "*.vsix" | grep -vE '\.(linux|windows)\.vsix' | head -n 1)
+          NEW_VSIX_FILE="${VSIX_FILE%.vsix}.linux.vsix"
+          mv $VSIX_FILE $NEW_VSIX_FILE
+          echo "LINUX_VSIX_FILE=$NEW_VSIX_FILE" >> $GITHUB_ENV
 
       - name: Package with VSCE
         run: npm run package
