Refactor report generation and evaluation steps
Combined report generation and evaluation into a single step, ensuring consistent execution flow and proper error tracking. Un-commented file write logic in `run_evaluation.py` to save errors.

diff --git a/.github/workflows/run-tests-workflow.yml b/.github/workflows/run-tests-workflow.yml
--- a/.github/workflows/run-tests-workflow.yml
+++ b/.github/workflows/run-tests-workflow.yml
@@ -81,33 +81,29 @@ jobs:
           ./ci/reqs2tests_eval.sh
         shell: bash
 
-      - name: Generate reports
+      - name: Upload reports and show summary
+        if: always()
         run: |
+          CODE=0
           source $VCAST_USER_HOME/.venv/bin/activate
           python evaluation/create_report.py --input ${{ env.VCAST_USER_HOME }}/.envs/r2t_eval_results --output ${{ env.VCAST_USER_HOME }}/.envs/report.html
           markdownify ${{ env.VCAST_USER_HOME }}/.envs/report.html > ${{ env.VCAST_USER_HOME }}/.envs/results.md
+          python ./ci/run_evaluation.py ${{ env.VCAST_USER_HOME }}/.envs/r2t_eval_results
+          CODE=$?
           deactivate
-        shell: bash
-
-      - name: Run evaluation
-        if: always()
-        run: |
-          python3.10 ./ci/run_evaluation.py ${{ env.VCAST_USER_HOME }}/.envs/r2t_eval_results
+          
           echo '## Run checks' >> $GITHUB_STEP_SUMMARY
           echo '```' >> $GITHUB_STEP_SUMMARY
           if [[ -f requirements_check_errors.txt ]] ; then
             echo "Errors found in requirements_check_errors.txt"
             cat requirements_check_errors.txt >> $GITHUB_STEP_SUMMARY
             echo '```' >> $GITHUB_STEP_SUMMARY
-            exit 1
+            CODE=1
+          else
+            echo 'No errors found' >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
           fi
-          echo 'No errors found' >> $GITHUB_STEP_SUMMARY
-          echo '```' >> $GITHUB_STEP_SUMMARY
-        shell: bash
-
-      - name: Upload reports
-        if: always()
-        run: |
+          
           COMMIT_DATE=$(git log -1 --format=%cd --date=format:%Y-%m-%dT%H:%M:%S)
           BASE_ARTIFACTORY_URL="https://artifactory.vi.vector.int:443/artifactory/rds-build-packages-generic-dev/code2reqs2tests/tests-results/${{ github.ref_name }}/$COMMIT_DATE-${{ github.sha }}/${{ env.ENV_SET_NAME }}"
           REPORT_URL=$BASE_ARTIFACTORY_URL/report.html
@@ -125,4 +121,6 @@ jobs:
           
           echo "## Markdown results" >> $GITHUB_STEP_SUMMARY
           cat ${{ env.VCAST_USER_HOME }}/.envs/results.md >> $GITHUB_STEP_SUMMARY
+          
+          exit $CODE
         shell: bash
