test

diff --git a/.github/workflows/run-tests-workflow.yml b/.github/workflows/run-tests-workflow.yml
--- a/.github/workflows/run-tests-workflow.yml
+++ b/.github/workflows/run-tests-workflow.yml
@@ -35,54 +35,64 @@ jobs:
       options: --user vcast_user --mount type=bind,source=${{ vars.VCAST_RELEASES_PATH }},target=/vcast
 
     steps:
-      - name: Check out repository
-        id: checkout
-        uses: actions/checkout@v4
-        continue-on-error: true
-
-      - name: Wait before retry
-        id: should-retry-checkout
-        if: failure()
-        continue-on-error: true
-        run: |
-          sleep 10
-          exit 1
-
-      - name: Check out repository (retry)
-        if: failure()
-        uses: actions/checkout@v4
-
-      - name: Virtual environment restore from cache
-        uses: actions/cache/restore@v4
-        id: cache-venv-restore
-        with:
-          path: ${{ env.VCAST_USER_HOME }}/.venv/
-          key: ${{ runner.os }}-venv-${{ hashFiles('./requirements.txt') }}
-
-      - name: Setup Python virtual environment
-        if: steps.cache-venv-restore.outputs.cache-hit != 'true'
-        run: |
-          python3.10 -m venv ${{ env.VCAST_USER_HOME }}/.venv
-          source ${{ env.VCAST_USER_HOME }}/.venv/bin/activate
-          pip install --no-cache --upgrade pip
-          pip install --no-cache --editable .
-          deactivate
-        shell: bash
-
-      - name: Virtual environment save cache
-        if: steps.cache-venv-restore.outputs.cache-hit != 'true'
-        uses: actions/cache/save@v4
-        with:
-          path: ${{ env.VCAST_USER_HOME }}/.venv/
-          key: ${{ runner.os }}-venv-${{ hashFiles('./requirements.txt') }}
-
-      - name: Reqs2tests evaluation
-        run: |
-          ./ci/reqs2tests_eval.sh
+      - name: test
+        run: tar -cf test.tar -T /dev/null
         shell: bash
 
       - name: Upload results artifact
-        uses: actions/upload-artifact@v3-node20
+        uses: actions/upload-artifact@v4
         with:
-          name: evaluation-results
-          path: ${{ env.VCAST_USER_HOME }}/.envs/r2t_eval_results
+          name: test
+          path: test.tar
+#
+#      - name: Check out repository
+#        id: checkout
+#        uses: actions/checkout@v4
+#        continue-on-error: true
+#
+#      - name: Wait before retry
+#        id: should-retry-checkout
+#        if: failure()
+#        continue-on-error: true
+#        run: |
+#          sleep 10
+#          exit 1
+#
+#      - name: Check out repository (retry)
+#        if: failure()
+#        uses: actions/checkout@v4
+#
+#      - name: Virtual environment restore from cache
+#        uses: actions/cache/restore@v4
+#        id: cache-venv-restore
+#        with:
+#          path: ${{ env.VCAST_USER_HOME }}/.venv/
+#          key: ${{ runner.os }}-venv-${{ hashFiles('./requirements.txt') }}
+#
+#      - name: Setup Python virtual environment
+#        if: steps.cache-venv-restore.outputs.cache-hit != 'true'
+#        run: |
+#          python3.10 -m venv ${{ env.VCAST_USER_HOME }}/.venv
+#          source ${{ env.VCAST_USER_HOME }}/.venv/bin/activate
+#          pip install --no-cache --upgrade pip
+#          pip install --no-cache --editable .
+#          deactivate
+#        shell: bash
+#
+#      - name: Virtual environment save cache
+#        if: steps.cache-venv-restore.outputs.cache-hit != 'true'
+#        uses: actions/cache/save@v4
+#        with:
+#          path: ${{ env.VCAST_USER_HOME }}/.venv/
+#          key: ${{ runner.os }}-venv-${{ hashFiles('./requirements.txt') }}
+#
+#      - name: Reqs2tests evaluation
+#        run: |
+#          ./ci/reqs2tests_eval.sh
+#        shell: bash
+#
+#      - name: Upload results artifact
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: evaluation-results
+#          path: ${{ env.VCAST_USER_HOME }}/.envs/r2t_eval_results
