Add script to fetch and extract latest reqs2tests release
Introduce a Python script to download the latest reqs2tests distribution from Artifactory. Integrate this step into the CI workflow to ensure the latest release is pulled, extracted, and stored in the appropriate directory for further use.

diff --git a/.github/workflows/run-tests-workflow.yml b/.github/workflows/run-tests-workflow.yml
--- a/.github/workflows/run-tests-workflow.yml
+++ b/.github/workflows/run-tests-workflow.yml
@@ -70,6 +70,17 @@ jobs:
             node_modules
           key: ${{ runner.os }}-dependencies-${{ hashFiles('package.json') }}
 
+      - name: Pull latest reqs2tests release
+        shell: bash
+        run: |
+          python3 ./ci/get_most_recent_reqs2tests_distribution.py
+          if [ ! -f "autoreq-linux.tar.gz" ]; then
+            echo "Error: autoreq-linux.tar.gz not found."
+            exit 1
+          fi
+          tar -xf autoreq-linux.tar.gz
+          mv distribution ./resources/distribution
+
       - name: Package with VSCE
         run: npm run package
 
